🔧 fix(.gitlab-ci.yml): Comment out 'dev' and 'prod' stages and their triggers

diff --git a/gitlab/ci/release.yml b/gitlab/ci/release.yml
--- a/gitlab/ci/release.yml
+++ b/gitlab/ci/release.yml
@@ -75,15 +75,23 @@ release:
     - |
       curl --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
            --upload-file app-release.apk \
-           "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/reactnative/${CI_COMMIT_TAG}/app-release.apk" \
+           "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/reactnative/${CI_COMMIT_TAG:-latest}/app-release.apk" \
            > upload_response.json
-    - FILE_URL=$(jq -r '.url' upload_response.json)
-    - '[ -z "$FILE_URL" ] && echo "Error: Failed to upload APK." && exit 1 || echo "APK uploaded successfully: $FILE_URL"'
+      FILE_URL=$(jq -r '.url // empty' upload_response.json)
+      if [ -z "$FILE_URL" ]; then
+      echo "Error: Failed to upload APK. Check upload_response.json for details:";
+      cat upload_response.json;
+      exit 1;
+      else
+      echo "APK uploaded successfully: $FILE_URL";
+      fi
+    - TAG_NAME=${CI_COMMIT_TAG:-"default-tag-name"}
     - echo "Creating GitLab release..."
     - |
       release-cli create \
-        --name "Release ${CI_COMMIT_TAG}" \
-        --tag-name "${CI_COMMIT_TAG}" \
+        --name "Release ${TAG_NAME}" \
+        --tag-name "${TAG_NAME}" \
         --ref "${CI_COMMIT_SHA}" \
-        --assets-link '{"name":"Release APK", "url":"'${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/reactnative/${CI_COMMIT_TAG}/app-release.apk'", "link_type":"other"}'
+        --assets-link "{\"name\":\"Release APK\", \"url\":\"${FILE_URL}\", \"link_type\":\"other\"}"
     - echo "GitLab release created successfully!"
+
